version: 2.1

jobs:
  build-libglez:
    docker:
      - image: ubuntu:22.04 # LTS only
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run:
          name: "Update apt and Install git"
          command: "apt update && apt install -y git"
      - run:
          name: "Clone freetype-gl"
          command: "git clone -b 85d7850744465ac1dcd00b202787d72a4a3a1f5d https://github.com/rougier/freetype-gl freetype-gl"
      - run:
          name: "Install freetype-gl packages"
          command: "apt install -y build-essential cmake libglew-dev libgl-dev libx11-dev libxext-dev libxfixes-dev libfreetype-dev"
      - run:
          name: "Make build directory"
          command: "mkdir freetype-gl/build"
      - run:
          name: "CMake build files"
          command: "cd freetype-gl/build && cmake -DCMAKE_BUILD_TYPE=Release -DOpenGL_GL_PREFERENCE=GLVND -Dfreetype-gl_BUILD_SHARED=ON ../"
      - run:
          name: "Build freetype-gl"
          command: "cd freetype-gl/build && make"
      - run:
          name: "Install freetype-dl"
          command: "cd freetype-dl/build && make install"
      - run:
          name: "Remove freetype-dl source"
          command: "rm -rf freetype-dl/"

      - checkout
      - run:
          name: "Install development packages"
          command: "apt install -y libz-dev libpng-dev libsdl2-dev"
      - run:
          name: "Make build directory"
          command: "mkdir build"
      - run:
          name: "CMake build files"
          command: "cd build && cmake -DCMAKE_BUILD_TYPE=Release ../"
      - run:
          name: "Build Project"
          command: "cd build && make"

workflows:
  build-libpdraw-workflow:
    jobs:
      - build-libglez
